# Generated by Django 2.0.6 on 2018-07-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='title',
            new_name='Title',
        ),
    ]
