# Generated by Django 2.0.6 on 2018-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20180714_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becometutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('CollegeName', models.CharField(max_length=250)),
                ('Subjects', models.CharField(max_length=150)),
            ],
        ),
    ]
