# Generated by Django 2.0.6 on 2018-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_becometutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoradmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=250)),
                ('Subjects', models.CharField(max_length=250)),
                ('Stream', models.CharField(max_length=250)),
                ('About', models.CharField(max_length=1000)),
                ('Fullabout', models.CharField(max_length=2500)),
            ],
        ),
    ]
