# Generated by Django 2.0.6 on 2018-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_selectsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectsubject',
            name='subject',
            field=models.CharField(choices=[('STATISTICS', 'Statistics'), ('PROGRAMMING', 'Programming'), ('PHYSICS', 'Physics'), ('CHEMICAL', 'Chemical Engineering'), ('ANDROID', 'Android'), ('BIOLOGY', 'Biology'), ('CIVIL', 'Civil Engineering'), ('CHEMICAL', 'Chemistry'), ('COMPUTER', 'Computer Science'), ('ENGLISH', 'English'), ('ECONOMICS', 'Economics'), ('ELECTRICAL', 'Electrical Engineering'), ('MATHS', 'Maths'), ('MATLAB', 'Matlab'), ('MECHANICAL', 'Mechanical Engineering'), ('R', 'R')], max_length=35),
        ),
    ]
